### ISSUE TITLE
访问网址出现404

### ISSUE THREAD

**Issue by cniop** [rain-dl/real-url-proxy-server#11]
启动 ： python real-url-proxy-server.py -p 8000
启动成功。
斗鱼ID:  特辑电影院,3637778,

浏览器输入：http://127.0.0.1:8000/douyu/3637778 
命令窗口显示：“Get  /douyu/3637778 HTTP /1.1" 404
 INFO: provider: douyu, room:3637778, bit_rate:None

**虎牙也是404：**

http://127.0.0.1:8000/huya/11342424

**Comment by ixinshang** [comment]
参考下这个
https://github.com/rain-dl/real-url-proxy-server/issues/10

**Comment by cniop** [comment]
> 参考下这个 #10

多谢！多谢！已经解决了，是我本地开着vpn代理的原因，把代理关了就正常了。
