### ISSUE TITLE
b站好像获取不了

### ISSUE THREAD

**Issue by smallwhitedesu1** [rain-dl/real-url-proxy-server#18]
报错了
![QQ截图20221010034128](https://user-images.githubusercontent.com/103363926/194776406-c760cb5d-2480-4747-8658-4b4d08d684d3.png)

**Comment by ixinshang** [comment]
我测试了一下，好像也不行。 这是日志
```
2022-10-10 06:02:44,706 - INFO: provider: bilibili, room: 5853237, bit_rate: None
XXX.149 - - [10/Oct/2022 06:02:44] "GET /bilibili/5853237 HTTP/1.1" 404 -
XXX.149 - - [10/Oct/2022 06:02:46] "GET /favicon.ico HTTP/1.1" 404 -
```
我记得有些房间有类似的短ID或者短名字。 我没找到。

**Comment by ixinshang** [comment]
另外，这个问题，我建议去这儿问。
https://github.com/wbt5/real-url

**Comment by rain-dl** [comment]
已经修复了这类直播间无法获取地址的问题，但获取到的地址在读取ts片段时会报404错误，无法播放。这应该是Bilibili的问题，我尝试用手机浏览器加载这个直播间，同样无法播放。之前B站无法播放也是同样的问题。
经过尝试，我发现只有一种fmp4格式的地址是可以播放的，有些直播间有这种格式的流，而有些就没有。这个5853237就没有fmp4格式的地址，所以无法播放。

**Comment by ixinshang** [comment]
> 已经修复了这类直播间无法获取地址的问题，但获取到的地址在读取ts片段时会报404错误，无法播放。这应该是Bilibili的问题，我尝试用手机浏览器加载这个直播间，同样无法播放。之前B站无法播放也是同样的问题。 经过尝试，我发现只有一种fmp4格式的地址是可以播放的，有些直播间有这种格式的流，而有些就没有。这个5853237就没有fmp4格式的地址，所以无法播放。

好的，不知道B站有这类区别对待。
