### ISSUE TITLE
请教一下REFRESH参数

### ISSUE THREAD

**Issue by trytrytogo** [rain-dl/real-url-proxy-server#19]
刚看到有更新，“[避免短时间内重复获取直播源地址。](https://github.com/rain-dl/real-url-proxy-server/commit/2d18bf3b86a432cf54ea8e75e8b6665ea9e30a95)”

目前自己打包的容器镜像，设置的刷新时间为600s。
想请教一下这个时间是否是必须值，有建议的参考值吗？

**Comment by ixinshang** [comment]
> 这个是设置后台间隔多长时间自动刷新直播源地址。 由于直播源基本都采取了防盗链措施，每次获取到的地址是有时效性的，一般最长不会超过24小时。如果不自动刷新的话，可能会导致直播源失效。 我自己目前设置为7200秒，即每两小时刷新一次。

好的，谢谢
