### ISSUE TITLE
请教下，手动运行python douyu.py获取到的播放地址每天都会变是吗？

### ISSUE THREAD

**Issue by zhuweijia** [rain-dl/real-url-proxy-server#22]
请教下，手动运行python douyu.py获取到的播放地址每天都会变是吗？
有啥办法，可以获取到固定的地址吗？就是每天看同一个直播间不用每次都要运行douyu.py获取新的地址？

新手一个，还不太懂这个，见谅。

**Comment by zhuweijia** [comment]
我看了下其他的issue，大概知道了，需要在一个服务器上部署你这个server端，再通过ip+端口号的形式直接访问，就可以了是吧。
不过我的路由器是华为的，不能部署，也没有本地服务器可以部署，感觉没啥招了

**Comment by rain-dl** [comment]
斗鱼、虎牙和Bilibili都有防盗链措施，每次获取到的地址只有几个小时有效，所以必须部署为服务端，定时去更新。
如果是用电脑看，那装在本机运行就行。
如果要用电视盒子看的话，那必须有个电脑或者可以运行Openwrt的路由器，家里没有的话，云服务器也可以。
或者你可以上闲鱼买个云帆流量宝盒M1、迅雷赚钱宝Pro之类的小盒子，刷成Openwrt。
还可以买个百元以内的瘦客户机作为小服务器用，还可以挂硬盘作为NAS。
