### ISSUE TITLE
关于斗鱼CDN的获取

### ISSUE THREAD

**Issue by guyijie1211** [rain-dl/real-url-proxy-server#29]
最近斗鱼的CDN总是失效，请问有说明办法获取到可用的CDN么

**Comment by rain-dl** [comment]
我并不清楚最早这种FLV的服务器地址是如何找到的，我目前采用的是最简单粗暴的办法：在ip138中搜douyucdn.cn和douyucdn2.cn的子域名，然后用脚本自动搜索哪个地址能够读取到视频信息，最后再手工检查实际是否可用。

**Comment by guyijie1211** [comment]
ok，感谢
