### ISSUE TITLE
douyu有些房间解析404

### ISSUE THREAD

**Issue by ixinshang** [rain-dl/real-url-proxy-server#3]
你好，作者。
目前我使用最新版的real-url-proxy-server,在解析一些douyu的房间的时候，出现404错误。解析环境。
极路由2 padavan，Python 3.9.0，错误代码：
![image](https://user-images.githubusercontent.com/10056396/110405202-1f084a80-8078-11eb-8181-f4656a37e727.png)
播放器测试效果：
![image](https://user-images.githubusercontent.com/10056396/110405267-3a735580-8078-11eb-9cb5-24883c84756d.png)

而后我在windows测试，
Python 3.9.1 
能正常解析出来。
![image](https://user-images.githubusercontent.com/10056396/110405385-70183e80-8078-11eb-94a3-c77d383b2e7a.png)
之前还有一台centos8的服务器，测试情况和极路由2一样。 由于机器已销毁，暂时没有详细的报错内容。
测试参数均为：python3 real-url-proxy-server.py -p 20098 -r 60
测试房间：/douyu/1392210
测试期间，斗鱼房间正常播放，且能通过浏览器正常访问。
最后请指教一下是否是我的使用不当导致的。
最后，感谢您开发维护分享这个项目。

**Comment by rain-dl** [comment]
我在Ubuntu和Padavan上试了这个房间号，解析都没有问题。
你运行python3 douyu.py，然后输入房间号，看看是否能解析出地址。

**Comment by ixinshang** [comment]
> 我在Ubuntu和Padavan上试了这个房间号，解析都没有问题。
> 你运行python3 douyu.py，然后输入房间号，看看是否能解析出地址。

我只有白天再测试了，现在手边没设备。
另外有些解析慢，都有些什么因素影响这个解析呢。

**Comment by rain-dl** [comment]
从douyu.py的代码来看，有些房间有hls地址，这些房间直接从返回的网页内容就能解析地址，速度很快。另外大部分房间则需要进一步调用返回的网页中的js代码才能得到播放地址，需要两次编译和调用js函数，在路由器这样的设备上速度就会很慢。
这几个解析地址的代码我也仅仅是拿来使用，没具体研究过。

**Comment by ixinshang** [comment]
可能是我的路由器性能不行   
最后感谢开发
