### ISSUE TITLE
斗鱼现在使用m3u8后，是只能获取900p和2000p的码率了么

### ISSUE THREAD

**Issue by guyijie1211** [rain-dl/real-url-proxy-server#30]
似乎不能直接修改链接上加 _4000这样的后缀来修改码率了

**Comment by rain-dl** [comment]
现在调用斗鱼API获取地址时给入的码率参数是-1，我测试发现获取的地址应该是该直播源的最高质量播放地址。所以目前给出的2000p其实是不准确的。不过，我尝试了修改码率参数，可获取到的地址的播放质量并没有改变，不清楚是什么原因。
