### ISSUE TITLE
bilibili 服务挂掉了

### ISSUE THREAD

**Issue by SunMacArenas** [rain-dl/real-url-proxy-server#33]
bilibili.py 脚本无法使用，需要在s.get 中添加headers ,请求才能通过。
header参考：
 self.header = {
            'User-Agent': 'Mozilla/5.0 (iPod; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.163 Mobile/15E148 Safari/604.1',
        }
param 参数内容也有调整，
param内容参考：
 params = {
                    'device': 'pc',
                    'platform': 'h5',
                    'scale': 0,
                    'build': '10000',
                    'protocol': '0,1',
                    'format': '0,1,2',
                    'codec': '0,1',
                    'room_id': room_id,
                    'qn': 10000
                }

**Comment by rain-dl** [comment]
抱歉，刚看到，已更新。
