### ISSUE TITLE
虎牙也G了

### ISSUE THREAD

**Issue by HelloGitHubWeb** [rain-dl/real-url-proxy-server#36]
虎牙也G了

**Comment by rain-dl** [comment]
斗鱼和虎牙我这里都没问题。
有问题把房间号发出来。

**Comment by HelloGitHubWeb** [comment]
斗鱼5232 虎牙660000 谢了

**Comment by x-xx-xxx-xxxx** [comment]
http://xxx.xxx.xxx.xxx/douyu/1226741
http://xxx.xxx.xxx.xxx/bilibili/22087974
路径没有问题啊!!!
douyu 1226741
bilibili 22087974
我这里都不行...

上面那个朋友说huya/660000有问题,我这可以正常播放
http://xxx.xxx.xxx.xxx/huya/660000

**Comment by x-xx-xxx-xxxx** [comment]
我这里只有huya没有问题,douyu和bilibili都不能使用~~~~难道是服务器问题???

**Comment by rain-dl** [comment]
斗鱼5232、虎牙660000、斗鱼1226741我这里试了都没有问题。
哔哩哔哩22087974没开播。

**Comment by x-xx-xxx-xxxx** [comment]
我这里重新弄了一下,虎牙和bili正常了,就是douyu有问题,,应该是获取不到房间号,我输入的房间号是对的啊....
这个房间号1226741是  粤语电影】吴孟达 达叔 周星驰 经典~~~
192.168.1.37 - - [12/Jan/2024 00:53:17] "GET /douyu/1226741 HTTP/1.1" 404 -
2024-01-12 00:55:17,677 - INFO: provider: douyu, room: 1226741, bit_rate: None
192.168.1.37 - - [12/Jan/2024 00:55:17] "GET /douyu/1226741 HTTP/1.1" 404 -

**Comment by iizyd** [comment]
> 我这里重新弄了一下,虎牙和bili正常了,就是douyu有问题,,应该是获取不到房间号,我输入的房间号是对的啊.... 这个房间号1226741是 粤语电影】吴孟达 达叔 周星驰 经典~~~ 192.168.1.37 - - [12/Jan/2024 00:53:17] "GET /douyu/1226741 HTTP/1.1" 404 - 2024-01-12 00:55:17,677 - INFO: provider: douyu, room: 1226741, bit_rate: None 192.168.1.37 - - [12/Jan/2024 00:55:17] "GET /douyu/1226741 HTTP/1.1" 404 -

怎么整的呀？我这边虎牙播放5秒左右就不行了

**Comment by x-xx-xxx-xxxx** [comment]
> > 我这里重新弄了一下,虎牙和bili正常了,就是douyu有问题,,应该是获取不到房间号,我输入的房间号是对的啊.... 这个房间号1226741是 粤语电影】吴孟达 达叔 周星驰 经典~~~ 192.168.1.37 - - [12/Jan/2024 00:53:17] "GET /douyu/1226741 HTTP/1.1" [404 - 2024-01-12](tel:404 - 2024-01-12) 00:55:17,677 - INFO: provider: douyu, room: [1226741](tel:1226741), bit_rate: None 192.168.1.37 - - [12/Jan/2024 00:55:17] "GET /douyu/1226741 HTTP/1.1" 404 -
> 
> 怎么整的呀？我这边虎牙播放5秒左右就不行了

我这里一开始虎牙就没有问题，我觉得你还是运行有问题，请问你是怎么运行这些py程序的？

**Comment by iizyd** [comment]
> > > 我这里重新弄了一下,虎牙和bili正常了,就是douyu有问题,,应该是获取不到房间号,我输入的房间号是对的啊.... 这个房间号1226741是 粤语电影】吴孟达 达叔 周星驰 经典~~~ 192.168.1.37 - - [12/Jan/2024 00:53:17] "GET /douyu/1226741 HTTP/1.1" [404 - 2024-01-12](tel:404 - 2024-01-12) 00:55:17,677 - INFO: provider: douyu, room: 1226741, bit_rate: None 192.168.1.37 - - [12/Jan/2024 00:55:17] "GET /douyu/1226741 HTTP/1.1" 404 -
> > 
> > 
> > 怎么整的呀？我这边虎牙播放5秒左右就不行了
> 
> 我这里一开始虎牙就没有问题，我觉得你还是运行有问题，请问你是怎么运行这些py程序的？

现在都弄好啦，斗鱼是直接走的douyu.py，虎牙是走的real-url-proxy-server代理，目前都正常啦

**Comment by x-xx-xxx-xxxx** [comment]
> > > > > 我这里重新弄了一下,虎牙和bili正常了,就是douyu有问题,,应该是获取不到房间号,我输入的房间号是对的啊.... 这个房间号1226741是 粤语电影】吴孟达 达叔 周星驰 经典~~~ 192.168.1.37 - - [12/Jan/2024 00:53:17] "GET /douyu/1226741 HTTP/1.1" [404 - 2024-01-12](tel:404 - 2024-01-12) 00:55:17,677 - INFO: provider: douyu, room: 1226741, bit_rate: None 192.168.1.37 - - [12/Jan/2024 00:55:17] "GET /douyu/1226741 HTTP/1.1" 404 -
> > > > 
> > > > 
> > > > 怎么整的呀？我这边虎牙播放5秒左右就不行了
> > > 
> > > 
> > > 我这里一开始虎牙就没有问题，我觉得你还是运行有问题，请问你是怎么运行这些py程序的？
> > 
> > 
> > 现在都弄好啦，斗鱼是直接走的douyu.py，虎牙是走的real-url-proxy-server代理，目前都正常啦
> 
> 嗯,好就行了

能详细说说斗鱼怎么走的吗,我这里斗鱼一直有问题,其他两个都可以,郁闷~~
