### ISSUE TITLE
请问下一下参数在哪运行呢

### ISSUE THREAD

**Issue by LNai** [rain-dl/real-url-proxy-server#5]
本人纯小白 刚刚把python3和模块装好 可以打开douyu.py文件获得直播源,但是以下参数不懂在哪里输入来获得直播源
python3 real-url-proxy-server.py [-h] -p PORT -r REFRESH  打开real-url-proxy-server.py直接提示错误 望开发大佬不吝赐教

**Comment by rain-dl** [comment]
使用方法看README.md中的“访问”。
错误轻给出错误信息。

**Comment by LNai** [comment]
> 使用方法看README.md中的“访问”。
> 错误请给出错误信息。

感谢回复 这几天比较忙抱歉 IDLE Shell 提示报错 usage: real-url-proxy-server.py [-h] -p PORT [-r REFRESH]
real-url-proxy-server.py: error: the following arguments are required: -p/--port 这个端口号是什么呢 该填写什么呢

**Comment by rain-dl** [comment]
启动：./real-url-proxy-server.py -p 8089 -r 7200
播放：mpv http://127.0.0.1:8089/huya/11342412
