### ISSUE TITLE
请问可以禁用缓存吗

### ISSUE THREAD

**Issue by moluanshanhe** [rain-dl/real-url-proxy-server#7]
自己家用，不暴露在公网，请问有什么办法可以禁用缓存，我设置了3600s的自动刷新，但是它好像不起作用，手动刷新需要指定房间号，太过于麻烦

**Comment by moluanshanhe** [comment]
抱歉，自动刷新是起作用的，它会在指定时间刷新所有的记录，但是如果直播间没有开播导致没有获取到新地址，那么依然会返回缓存的地址

**Comment by rain-dl** [comment]
这么处理是为了避免偶尔的一次访问失败造成再次刷新之前一直无法访问。

**Comment by moluanshanhe** [comment]
已经找到其它项目解决此问题，谢谢

**Comment by ixinshang** [comment]
> 已经找到其它项目解决此问题，谢谢

啥项目呢

**Comment by moluanshanhe** [comment]
硬盘卖了  现在找不着了 你可以留个邮箱 找到了我发你
