### ISSUE TITLE
虎牙的看一会好像还是会403，我用的是房间号11342412测试的，虎牙的一起看目前是不是无解呢

### ISSUE THREAD

**Issue by wtf0404** [rain-dl/real-url-proxy-server#8]

**Comment by rain-dl** [comment]
确认你用的是否是最新版本，我这里鹿鼎记都看完了也没问题啊。

**Comment by wtf0404** [comment]
> 确认你用的是否是最新版本，我这里鹿鼎记都看完了也没问题啊。

不好意思才看到回复，刚我又重新下载了最新的python代码，跑起来的地址看了几分钟就403了，看附件图，我用的是VLC播放器
![403](https://user-images.githubusercontent.com/81900833/129486427-d942ce63-f592-4ff7-9642-2439e50bc0d9.png)

**Comment by wtf0404** [comment]
应该是我用错了，我是直接用的huya.py生成的地址来播放的，所以过一会就403了。用了你的real-url-proxy-server.py代理后应该没问题了。想问问大佬，如果我自己想用别的语言来实现这个huya代理的话，思路应该是每隔一段时间通过huya.py来获取实际地址，读取m3u8内容即可吧

**Comment by rain-dl** [comment]
你看看代码就知道了，从虎牙服务器返回的是一些基础信息，用于计算生成防盗链地址。我目前的做法是每两分钟重新计算一次防盗链地址，这个过程中使用的是已经保存下来的服务器返回的信息，而不是每次去访问虎牙。服务器信息是按命令行给进的刷新间隔进行刷新的。

**Comment by wtf0404** [comment]
好的，感谢大佬回复
