### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by guyijie1211** [rain-dl/real-url-proxy-server#9]
部署在服务器上，使用浏览器播放会有跨域问题，不知道是否有解决方法

**Comment by rain-dl** [comment]
抱歉，刚看到。
你说的跨域问题我确实不懂，把部署环境和错误信息描述一下吧。

**Comment by guyijie1211** [comment]
就是把这个项目部署在后端服务器上后，如果使用浏览器的播放器来播放的时候，会因为前后端ip不同而无法访问。在potplayer等播放器上没有问题。似乎是得返回的response head中增加一些跨域信息

**Comment by rain-dl** [comment]
添加了几个http头以尝试解决浏览器跨域问题，你同步最新代码试试看有没有效吧。

**Comment by guyijie1211** [comment]
可以了，十分感谢
